// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkOrderApp.AppDbContext;

#nullable disable

namespace WorkOrderApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427111925_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkOrderApp.Entities.BaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("WorkOrderApp.Entities.BaseEnum", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("BaseEnum");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.City", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Country", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("IsoCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.User", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Appliance", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Currency", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.FeeType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.Property<decimal>("PenaltyPercentage")
                        .HasColumnType("numeric");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.IdentificationType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("IdentificationTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.LeaseType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("LeaseTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.PaymentType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.PropertyType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.Property<bool>("IsCommercial")
                        .HasColumnType("boolean");

                    b.ToTable("PropertyTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Role", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.City", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
