// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorkOrderApp.AppDbContext;

#nullable disable

namespace WorkOrderApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("request_number_seq")
                .StartsAt(1000L);

            modelBuilder.HasSequence<int>("work_order_number_seq")
                .StartsAt(1000L);

            modelBuilder.Entity("WorkOrderApp.Entities.BaseEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("WorkOrderApp.Entities.UserLocation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("UserLocations");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Attachment", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkOrderId")
                        .HasColumnType("text");

                    b.HasIndex("RequestId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.BaseEnum", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("BaseEnum");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Cost", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Costs");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Location", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Part", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("QRCode")
                        .HasColumnType("text");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("QRCode");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Request", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("text");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('request_number_seq')");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("LocationId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("RequestedById");

                    b.HasIndex("Status");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.RequestLog", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("RequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.User", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.WorkOrder", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("AssignedById")
                        .HasColumnType("text");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("text");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstimatedTime")
                        .HasColumnType("integer");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('work_order_number_seq')");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("AssignedById");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.WorkOrderLog", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEntity");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewStatus")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkOrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderLogs");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Appliance", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("Appliances");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Currency", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.FeeType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.Property<decimal>("PenaltyPercentage")
                        .HasColumnType("numeric");

                    b.ToTable("FeeTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.IdentificationType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("IdentificationTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.LeaseType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("LeaseTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.PaymentType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("PaymentTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.PropertyType", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.Property<bool>("IsCommercial")
                        .HasColumnType("boolean");

                    b.ToTable("PropertyTypes");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Role", b =>
                {
                    b.HasBaseType("WorkOrderApp.Entities.BaseEnum");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.UserLocation", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.Location", "Location")
                        .WithMany("UserLocations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.User", "User")
                        .WithMany("UserLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Attachment", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.Request", "Request")
                        .WithMany("Attachments")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WorkOrderApp.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Attachments")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Request");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Cost", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Costs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Part", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Parts")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Request", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.RequestLog", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.Request", "Request")
                        .WithMany("Logs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.WorkOrder", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.User", "AssignedBy")
                        .WithMany()
                        .HasForeignKey("AssignedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkOrderApp.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkOrderApp.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.Request", "Request")
                        .WithOne("WorkOrder")
                        .HasForeignKey("WorkOrderApp.Entities.WorkOrder", "RequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedBy");

                    b.Navigation("AssignedTo");

                    b.Navigation("Customer");

                    b.Navigation("Location");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.WorkOrderLog", b =>
                {
                    b.HasOne("WorkOrderApp.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkOrderApp.Entities.WorkOrder", "WorkOrder")
                        .WithMany("Logs")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Location", b =>
                {
                    b.Navigation("UserLocations");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.Request", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Logs");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.User", b =>
                {
                    b.Navigation("UserLocations");
                });

            modelBuilder.Entity("WorkOrderApp.Entities.WorkOrder", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Costs");

                    b.Navigation("Logs");

                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
